spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_platform}
    username: ${DB_USERNAME:bank}
    password: ${DB_PASSWORD:bank}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: notification_service
    open-in-view: false
  flyway:
    schemas: notification_service
    default-schema: notification_service
    create-schemas: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
