spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${USER_SERVICE_JWKS_URI:http://localhost:8081/.well-known/jwks.json}

server:
  port: 8080

bank-platform:
  routes:
    user-service: ${USER_SERVICE_URI:http://localhost:8081}
    account-service: ${ACCOUNT_SERVICE_URI:http://localhost:8082}
    transaction-service: ${TRANSACTION_SERVICE_URI:http://localhost:8083}
    audit-service: ${AUDIT_SERVICE_URI:http://localhost:8088}
    payment-service: ${PAYMENT_SERVICE_URI:http://localhost:8084}
    reporting-service: ${REPORTING_SERVICE_URI:http://localhost:8087}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
