apiVersion: v1
kind: Secret
metadata:
  name: bank-platform-postgres
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.global.postgres.username | quote }}
  password: {{ .Values.global.postgres.password | quote }}
