spring:
  application:
    name: fraud-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    streams:
      application-id: fraud-service
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        num.stream.threads: 2

bank-platform:
  fraud:
    window-minutes: 10
    rules:
      max-transfer-count: 5
      max-transfer-amount: 50000

logging:
  structured:
    format:
      console: ecs

server:
  port: 8085
  tomcat:
    threads:
      max: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
