spring:
  application:
    name: fraud-service

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
