spring:
  application:
    name: account-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_platform}
    username: ${DB_USERNAME:bank}
    password: ${DB_PASSWORD:bank}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: account_service
    open-in-view: false
  flyway:
    schemas: account_service
    default-schema: account_service
    create-schemas: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${USER_SERVICE_JWKS_URI:http://localhost:8081/.well-known/jwks.json}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: account-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
